# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    ignore:
      - dependency-name: "*"
        # patch and minor updates don't matter for libraries as consumers of this library build
        # with their own lockfile, rather than the version specified in this library's lockfile
        # remove this ignore rule if your package has binaries to ensure that the binaries are
        # built with the exact set of dependencies and those are up to date.
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
